CREATE DATABASE INTERVIEW_WH;

CREATE USER USER_MICHAEL;

CREATE SCHEMA USER_MICHAEL;

USE INTERVIEW_WH;

USE SCHEMA USER_MICHAEL;

CREATE TABLE Airlines
(IATA_CODE VARCHAR(30),
 AIRLINE VARCHAR(255)
);

CREATE TABLE airports
(IATA_CODE VARCHAR(30),
AIRPORT VARCHAR(255),
CITY VARCHAR(30),
STATE VARCHAR(30),
COUNTRY VARCHAR(30),
LATITUDE FLOAT,
LONGITUDE FLOAT);


create table flights
(YEAR NUMBER,
MONTH NUMBER,
DAY NUMBER,
DAY_OF_WEEK NUMBER,
AIRLINE VARCHAR(30),
FLIGHT_NUMBER VARCHAR(255),
TAIL_NUMBER VARCHAR(255),
ORIGIN_AIRPORT VARCHAR(255),
DESTINATION_AIRPORT VARCHAR(255),
SCHEDULED_DEPARTURE NUMBER,
DEPARTURE_TIME NUMBER,
DEPARTURE_DELAY NUMBER,
TAXI_OUT NUMBER,
WHEELS_OFF NUMBER,
SCHEDULED_TIME NUMBER,
ELAPSED_TIME NUMBER,
AIR_TIME NUMBER,
DISTANCE NUMBER,
WHEELS_ON NUMBER,
TAXI_IN NUMBER,
SCHEDULED_ARRIVAL NUMBER,
ARRIVAL_TIME NUMBER,
ARRIVAL_DELAY NUMBER,
DIVERTED NUMBER,
CANCELLED NUMBER,
CANCELLATION_REASON VARCHAR(255),
AIR_SYSTEM_DELAY NUMBER,
SECURITY_DELAY NUMBER,
AIRLINE_DELAY NUMBER
);
